import React from "react";
import "./why-us.css";

// const steps = [
//   {
//     icon: "bi-lightbulb",
//     title: " Innovative Technology and Solutions",
//     description:
//       "We help customers connect and manage their devices, as well as solutions that help them analyse and make use of the data generated by those devices.",
//   },
//   {
//     icon: "bi-diagram-3",
//     title: "Smart Planning",
//     description:
//       "We simplify complex ideas into actionable strategies, ensuring a clear path from concept to execution.",
//   },
//   {
//     icon: "bi-rocket",
//     title: "Seamless Launch",
//     description:
//       "From development to deployment, we handle the details so you can focus on the big picture.",
//   },
//   {
//     icon: "bi-heart-pulse",
//     title: "Continuous Support",
//     description:
//       "We stay by your side with proactive maintenance, updates, and enhancements to keep you ahead.",
//   },
// ];

const steps = [
  {
    icon: "bi-lightbulb",
    title: "Innovative Technology and Solutions",
    description:
      "We help customers connect and manage their devices, and provide solutions that enable them to analyze and leverage the data those devices generate.",
  },
  {
    icon: "bi-shield-check",
    title: "Quality and Reliability",
    description:
      "We are committed to delivering exceptional customer service and dependable IoT solutions that perform consistently and exceed expectations.",
  },
  {
    icon: "bi-eye",
    title: "Transparency",
    description:
      "We’re open about how our products work and provide the tools and support our customers need to take control of their IoT journey.",
  },
  {
    icon: "bi-broadcast",
    title: "IoT Awareness",
    description:
      "By increasing awareness of IoT, we help individuals and organizations make smarter, more strategic decisions about adopting this technology.",
  },
];

export default function WhyChooseUs() {
  return (
    <div className="section">
      <div className="container">
        <div className="header-center">
          <h1 className="header-title">
            Why Innovate <span>With Us</span>
          </h1>
          <p className="title-explanation">
            we combine cutting-edge technology, deep expertise, and a user-first
            approach to make innovation simple and impactful. From idea to
            execution, we empower you with reliable solutions, transparent
            processes, and the tools you need to succeed in the connected world.
          </p>
        </div>
        <div className=" section steps-container">
          {steps.map((step, index) => (
            <div className="step-item" key={index}>
              <div className="step-icon">
                <i className={`bi ${step.icon}`}></i>
              </div>
              <h3 className="step-title">{step.title}</h3>
              <p className="step-description">{step.description}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
